export-pcb:
  image: docker.io/setsoft/kicad_auto:dev_k6
  script:
    - cd pcb
    - kibot -vvv -c ../revxlp.kibot.yaml
  artifacts:
    paths:
      - pcb/revxlp-JLCPCB.zip
      - pcb/revxlp_*.csv
