stages:
  - export
  - generate

export-pcb:
  stage: export
  image: docker.io/setsoft/kicad_auto:dev_k6
  script:
    - cd pcb
    - kibot -vvv
  artifacts:
    paths:
      - pcb/JLCPCB/revxlp-JLCPCB.zip
      - pcb/revxlp_*.csv
      - pcb/revxlp*.dxf

export-switch-plate:
  image: docker.io/setsoft/kicad_auto:dev_k6
  stage: export
  script:
    - cd plate
    - kibot -vvv
  artifacts:
    paths:
      - plate/JLCPCB/revxlp_plate-JLCPCB*.zip

export-bottom-plate:
  image: docker.io/setsoft/kicad_auto:dev_k6
  stage: export
  script:
    - cd bottom
    - kibot -vvv
  artifacts:
    paths:
      - bottom/revxlp_bottom-Edge_Cuts.dxf
      - bottom/JLCPCB/revxlp_bottom-JLCPCB*.zip
      - bottom/JLCPCB/revxlp_bottom-NPTH.drl
      - bottom/revxlp_bottom_*.csv

generate-3dp-case:
  image: cadquery/cadquery
  stage: generate

  script:
    - ./plate-case-export.py
    - ./plate-case-export.py --feature base
    - ./plate-case-export.py --feature logo
    - ./plate-case-export.py --feature button_cutouts

  artifacts:
    paths:
      - "*.step"
      - "*.stl"

generate-case-foam:
  image: python:3-alpine
  stage: generate
  needs:
    - export-bottom-plate
    - export-pcb

  before_script:
    - pip install ezdxf

  script:
    - ./case-foam-dxf-merge.py

  artifacts:
    paths:
      - "revxlp-case-foam.dxf"
