export-pcb:
  image: docker.io/setsoft/kicad_auto:dev_k6
  script:
    - cd pcb
    - kibot -vvv
  artifacts:
    paths:
      - pcb/JLCPCB/revxlp-JLCPCB.zip
      - pcb/revxlp_*.csv

export-plate:
  image: docker.io/setsoft/kicad_auto:dev_k6
  script:
    - cd plate
    - kibot -vvv
  artifacts:
    paths:
      - plate/JLCPCB/revxlp-JLCPCB.zip
      - plate/revxlp_*.csv
